### ISSUE TITLE
segment anything can't found

### ISSUE THREAD

**Issue by NTUYWANG103** [sczhou/ProPainter#68]
Traceback (most recent call last):
  File "/home/wangyuxi/codes/ProPainter/ProPainter/web-demos/hugging_face/app.py", line 17, in <module>
    from track_anything import TrackingAnything
  File "/home/wangyuxi/codes/ProPainter/ProPainter/web-demos/hugging_face/track_anything.py", line 4, in <module>
    from tools.interact_tools import SamControler
  File "/home/wangyuxi/codes/ProPainter/ProPainter/web-demos/hugging_face/tools/interact_tools.py", line 7, in <module>
    from segment_anything import sam_model_registry, SamPredictor, SamAutomaticMaskGenerator
ModuleNotFoundError: No module named 'segment_anything'

I didn't seach any predefined function for sam_model_registry, SamPredictor, SamAutomaticMaskGenerator, could u let me know should I clone from other repo or my problem?

**Comment by Luo-Yihang** [comment]
Hi, it appears that you have not installed the Python module `segment_anything`. To check the required pip modules for the web demo, refer to `./web-demos/hugging_face/requirements.txt`. You can install these requirements using the following command `pip3 install -r requirements.txt`. For additional details, please check the `./web/demos/hugging_face/README.md`. Feel free to reach out if you have any further questions.
