### ISSUE TITLE
I get an installation error for pip install mmcv-full 

### ISSUE THREAD

**Issue by terry** [sczhou/ProPainter#7]
the error message is as following:
Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /home/zhenhuaai/.conda/envs/propainter/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jalet417/mmcv-full_34951aab882f4e63a328b1c0c23cb237/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jalet417/mmcv-full_34951aab882f4e63a328b1c0c23cb237/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-x04zc70y
         cwd: /tmp/pip-install-jalet417/mmcv-full_34951aab882f4e63a328b1c0c23cb237/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jalet417/mmcv-full_34951aab882f4e63a328b1c0c23cb237/setup.py", line 403, in <module>
        ext_modules=get_extensions(),
      File "/tmp/pip-install-jalet417/mmcv-full_34951aab882f4e63a328b1c0c23cb237/setup.py", line 313, in get_extensions
        extra_compile_args=extra_compile_args)
      File "/home/zhenhuaai/.conda/envs/propainter/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 779, in CUDAExtension
        library_dirs += library_paths(cuda=True)
      File "/home/zhenhuaai/.conda/envs/propainter/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 869, in library_paths
        if (not os.path.exists(_join_cuda_home(lib_dir)) and
      File "/home/zhenhuaai/.conda/envs/propainter/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1783, in _join_cuda_home
        raise EnvironmentError('CUDA_HOME environment variable is not set. '
    OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/02/39/ef8b2c52e73a90df6cbb1e6fbd5eb374ee6d0a1888ed2e758a98098b479c/mmcv-full-1.4.8.tar.gz#sha256=329a68d80367901e68c1a2445beb09a72ed53700d7226e1199bbf5d12e91d506 (from https://pypi.org/simple/mmcv-full/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement mmcv-full==1.4.8 (from versions: 1.0rc0, 1.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3.0, 1.3.1, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.3.15, 1.3.16, 1.3.17, 1.3.18, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1)
ERROR: No matching distribution found for mmcv-full==1.4.8

failed

CondaEnvException: Pip failed

**Comment by terry** [comment]
The OS is ubuntu 22.04

**Comment by Fadexboss** [comment]
same error

**Comment by 21pl** [comment]
getting same error. Anybody able to resolve this?

**Comment by 21pl** [comment]
ok so stepping through the errors.
After the :
CondaEnvException: Pip failed
I run  
python inference_propainter.py --video inputs/object_removal/bmx-trees --mask inputs/object_removal/bmx-trees_mask

and each error i then pip install the package which errors out
so...
pip install opencv-python
pip install tqdm
pip install mmcv-full==1.4.8 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html
 pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
 pip install einops
 pip install imageio-ffmpeg
 python inference_propainter.py --video inputs/object_removal/bmx-trees --mask inputs/object_removal/bmx-trees_mask
 this now works!

**Comment by Fadexboss** [comment]
> ok so stepping through the errors. After the : CondaEnvException: Pip failed I run python inference_propainter.py --video inputs/object_removal/bmx-trees --mask inputs/object_removal/bmx-trees_mask
> 
> and each error i then pip install the package which errors out so...
> 
> pip install opencv-python
> 
> pip install tqdm
> 
> pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
> 
> pip install mmcv-full==1.4.8 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html
> 
> pip install einops
> 
> pip install imageio-ffmpeg
> 
> pip install av
> 
> python inference_propainter.py --video inputs/object_removal/bmx-trees --mask inputs/object_removal/bmx-trees_mask
> 
> this now works!

Worked! Thanks

**Comment by sczhou** [comment]
Hi @shinyrico , I just simply the installation by removing the mmcv and update the installation steps, please check it out:
https://github.com/sczhou/ProPainter#dependencies-and-installation

Same issues: #1 #7 #13 #20

**Comment by sczhou** [comment]
Hi @terry , I just simply the installation by removing the mmcv and update the installation steps, please check it out:
https://github.com/sczhou/ProPainter#dependencies-and-installation
