### ISSUE TITLE
The size of tensor a (200) must match the size of tensor b (201) at non-singleton dimension 1

### ISSUE THREAD

**Issue by rospin** [sczhou/ProPainter#84]
I encountered the following problem while processing a file named sss.mp4

Processing: sss_seg [200 frames]...
Traceback (most recent call last):
  File "D:\Users\xp\Apps\aiSoftware\watermark_remover_z\ProPainter\inference_propainter.py", line 372, in <module>
    masked_frames = frames * (1 - masks_dilated)
RuntimeError: The size of tensor a (200) must match the size of tensor b (201) at non-singleton dimension 1

**Comment by XiaoqiangZhou** [comment]
> I encountered the following problem while processing a .mp4 file
> 
> Processing: XXX_seg [200 frames]... Traceback (most recent call last): File "D:\Users\ProPainter\inference_propainter.py", line 372, in masked_frames = frames * (1 - masks_dilated) RuntimeError: The size of tensor a (200) must match the size of tensor b (201) at non-singleton dimension 1

do you know how to fix the bug? thx @rospin
