### ISSUE TITLE
Training phase

### ISSUE THREAD

**Issue by 1chuanchuan** [sczhou/ProPainter#87]
`(propainter) PS E:\gzh\Project\watermark-remove> python train.py -c configs/train_propainter.json
world_size: 1
[**] create folder experiments_model/propainter_train_propainter
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    mp.spawn(main_worker, nprocs=torch.cuda.device_count(), args=(config, ))
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\gzh\Project\watermark-remove\train.py", line 74, in main_worker
    trainer = core.__dict__[trainer_version].__dict__['Trainer'](config)
    self.train_dataset = TrainDataset(config['train_data_loader'])
  File "E:\gzh\Project\watermark-remove\core\dataset.py", line 43, in __init__
    frame_list = sorted(os.listdir(os.path.join(self.video_root, v)))
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\gzh\\Project\\watermark-remove\\datasets\\003234408d'

(propainter) PS E:\gzh\Project\watermark-remove> python train.py -c configs/train_propainter.json
world_size: 1
[**] create folder experiments_model/propainter_train_propainter
Pretrained flow completion model has loaded...
Network [InpaintGenerator] was created. Total number of parameters: 39.4 million. To see the architecture, do print(network).
Warnning: There is no trained model found.An initialized model will be used.
  0%|                                                                                                                                   | 0/700000 [00:00<?, ?it/s]D
:\Anaconda3\envs\propainter\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                   | 0/700000 [01:15<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    mp.spawn(main_worker, nprocs=torch.cuda.device_count(), args=(config, ))
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\gzh\Project\watermark-remove\train.py", line 76, in main_worker
    trainer.train()
  File "E:\gzh\Project\watermark-remove\core\trainer.py", line 345, in train
    self._train_epoch(pbar)
  File "E:\gzh\Project\watermark-remove\core\trainer.py", line 377, in _train_epoch
    prop_imgs, updated_local_masks = self.netG.module.img_propagation(masked_local_frames, pred_flows_bi, local_masks, interpolation=self.interp_mode)
  File "D:\Anaconda3\envs\propainter\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'InpaintGenerator' object has no attribute 'module'`
Hello, I encountered this problem when running the code, could you please tell me which file is the training model and where it is located?

**Comment by shenyewei** [comment]
请问你训练的时候花了多少时间？
